# Exercise 1 (Total recall)

Term | Brief Description
:--- | :---
Subsetting | The action of selecting from a set of data
Indexing | Selecting one element from a set of data
Slicing | Selecting multiple elements from a set of data
Masking | Hiding certain elements from a set of data

# Exercise 2 (Show me the 'odd' letters)

In [3]:
import numpy as np

In [4]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

In [12]:
np_array_2d[:,0]

array(['1', '3', '2', '4', '5', '7', '6', '8', '10', '9'], dtype='<U21')

In [13]:
a = np_array_2d[:,0]
int_a = a.astype(int)
print(int_a)

[ 1  3  2  4  5  7  6  8 10  9]


In [14]:
b = int_a%2
print(b)

[1 1 0 0 1 1 0 0 0 1]


In [15]:
c = b > 0
c

array([ True,  True, False, False,  True,  True, False, False, False,
        True])

In [23]:
np_array_2d[c, 1]

array(['A', 'C', 'E', 'G', 'I'], dtype='<U21')

# Exercise 3

In [25]:
np_array_2d = np.array([[66, 50, 57, -1, -1],
 [92, -1, 88, -1, -1],
 [75, -1, -1, 76, -1],
 [-1, 51, 87, -1, -1],
 [71, -1, 67, -1, 69]])

In [27]:
a = np_array_2d < 50
np_array_2d[a] = -1
b = np_array_2d > 50
np_array_2d[b] = 1
c = np_array_2d == 50
np_array_2d[c] = 0

print(np_array_2d)

[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
