In [3]:
import numpy as np

In [4]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

# Pick one
x = py_list  # OR
x = np_array

In [5]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3
my_mask

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [6]:
np_array[my_mask]

array([ 4,  5,  6,  7,  8,  9, 10])

In [7]:
np_array[np_array > 3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [8]:
np_array[~(np_array > 3)]                 # '~' means 'NOT'

array([1, 2, 3])

In [9]:
np_array[(np_array > 3) & (np_array < 8)] # '&' means 'AND'

array([4, 5, 6, 7])

In [10]:
np_array[(np_array < 3) | (np_array > 8)] # '|' means 'OR'

array([ 1,  2,  9, 10])

In [11]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)

In [12]:
py_list_2d[3]
np_array_2d[3]

array(['4', 'D'], dtype='<U21')

In [13]:
py_list_2d[3][0]
np_array_2d[3, 0]

np.str_('4')

In [14]:
py_list_2d[:3][0]
np_array_2d[:3, 0]

array(['1', '2', '3'], dtype='<U21')

In [15]:
py_list_2d[3:6][0]
np_array_2d[3:6, 0]
np_array_2d[:, 0]

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U21')

In [16]:
x=[1, 2]*5
x

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [17]:
x=[1]
x= x + [2]
x= x + [3]
x= x + [4]
x
x=[1]
x+= [2]
x+= [3]
x+= [4]
x
x=[1]
x.append(2)
x.append(3)
x.append(4)
x

[1, 2, 3, 4]

In [19]:
x = [1, 2, 3]
x += [4, 5, 6]
x

[1, 2, 3, 4, 5, 6]

In [20]:
x=[1, 2, 3]
x.extend([4, 5, 6])
x

[1, 2, 3, 4, 5, 6]

In [21]:
x=[1, 2, 3]
x.append([4, 5, 6])
x

[1, 2, 3, [4, 5, 6]]

In [22]:
a=(1, 2, 3)     # Define tuple

In [23]:
print(a[0])    # Access data

1


In [24]:
# The following will NOT work
a[0]=-1
a[0]+= [10]

TypeError: 'tuple' object does not support item assignment

In [25]:
x=[1, 2, 3]
y=x           # DON'T do this!
z=x           # DON'T do this!

In [26]:
x=[1, 2, 3]
y=x.copy()
z=x.copy()