In [1]:
import numpy as np

In [2]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

In [3]:
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

In [4]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}

In [5]:
py_real_names[0]

'Natasha Romanoff'

In [6]:
py_super_names[0]

'Black Widow'

In [7]:
py_super_names[2]    # Forward indexing 
                     # We need to know the size 
                     # beforehand for this to work.

'Doctor Strange'

In [8]:
py_super_names[-1]   # Reverse indexing

'Doctor Strange'

In [9]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}      

In [10]:
superhero_info["Natasha Romanoff"]


'Black Widow'

In [11]:
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]

In [12]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array

In [13]:
py_list_2d

[[1, 'A'],
 [2, 'B'],
 [3, 'C'],
 [4, 'D'],
 [5, 'E'],
 [6, 'F'],
 [7, 'G'],
 [8, 'H'],
 [9, 'I'],
 [10, 'J']]

In [14]:
np_array_2d

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C'],
       ['4', 'D'],
       ['5', 'E'],
       ['6', 'F'],
       ['7', 'G'],
       ['8', 'H'],
       ['9', 'I'],
       ['10', 'J']], dtype='<U21')

In [15]:
len(py_list_2d)

10

In [16]:
len(np_array_2d)

10

In [17]:
np_array_2d.shape

(10, 2)

In [18]:
py_list = [1, 1.5, 'A']
np_array = np.array(py_list)

In [19]:
py_list
np_array

array(['1', '1.5', 'A'], dtype='<U32')

In [20]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         # Reusing the Python list
                                     # to create a NEW
                                     # NumPy array

In [21]:
np_array + 10

array([11, 12, 13, 14, 15])

In [22]:
py_list + 10

TypeError: can only concatenate list (not "int") to list

In [23]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

In [25]:
np_array_1 + np_array_2

array([11, 22, 33, 44, 55])

In [26]:
py_list_1 + py_list_2

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [27]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)    

In [28]:
py_list*2


[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [29]:
np_array*2

array([ 2,  4,  6,  8, 10])

In [30]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [31]:
np_array**2

array([ 1,  4,  9, 16, 25])

In [32]:
py_list**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [33]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)   

In [34]:
py_list == 3

False

In [35]:
np_array == 3

array([False, False,  True, False, False])

In [36]:
np_array > 3

array([False, False, False,  True,  True])

In [37]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)    

In [38]:
sum(py_list)

15

In [39]:
max(py_list)

5

In [40]:
min(py_list)

1

In [41]:
np_array.sum()

np.int64(15)

In [42]:
np_array.max()

np.int64(5)

In [43]:
np_array.min()

np.int64(1)

In [44]:
np_array.mean()

np.float64(3.0)

In [45]:
np_array.std()

np.float64(1.4142135623730951)